sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
before_script:
- npm prune
after_success:
- npm run report-coverage
- curl -Lo travis_after_all.py https://git.io/travis_after_all
- python travis_after_all.py
- export $(cat .to_export_back) &> /dev/null
- npm run release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: R9izp6A7kdCVi8Oiji6RQ6PJFUqMkn/PO8F4PDSo183LRBrx6cug+JuOrInZkCV0m6o6alcAbFxMoaI1zGOl18Z9H31238VBrojqfAPvw2BN4Lxivnh3XXnzXcwDnA5CT2qf2SUekzHjvt3omKyQNXLLHM9ayasiLlFBwtfP2nQ=
  - secure: OIep1lrcBespZsD3w2CnEPVmu5O18Qy98PdApMkDuF5KnPydF7v4dDJioxHBdBvwMe3ZX3fmrjovPatj3+E5U9eVFXL8iTmknEcXiM85Jx3gtSRJPwNjjpDyUrzeAxDwgo0VNgzrOd6IEB2573HCu1dBKA+ZwrNp3lkbEmh2kgI=
  - secure: SkGkuhy/PRh3ogcq1Fmu5/ZDvSgHakBo/ROfdkiGmhQL/HcA9liHGkEykYdMmQtAtLmMwk8tCVeUoTYFRgi8kjyPfN33EvH3yQ1WCJh5xO3LyRfJTTQfAreCPaac7uYAIs7RH459Sm4DN3JhvCJ9+aLBtQDZkuHbxHe8PpwzH6I=
